### PR TITLE
Release/0.13.0rc2

### PR DESCRIPTION
**Pull request by kurtmckee**
Python support
--------------

-   Support Python 3.12.
-   Drop support for Python 3.7.

Development
-----------

-   Remove unused dependencies.

Dependencies
------------

-   Raise the minimum Flask version to 2.3.0, which dropped support for Python 3.7.

### CODE REVIEW

**Review by ada-globus — APPROVED** [review]

**Comment by sirosen** [comment]
I'm only seeing this now that we're doing the release PR -- can we add 3.12 to CI?
I'm surprised to see so few changes regarding metadata and test configs in a release which drops one version and adds another.

**Comment by kurtmckee** [comment]
*COUGH* looks okay to me *COUGH* :grin:

**Comment by sirosen** [comment]
I'll hide my comment as OT! :wink:

**Review by sirosen — APPROVED** [review]

**Review by ada-globus — APPROVED** [review]
Re-approved

**Pull request merged**
