### PR TITLE
Various improvements to docs

### PR DESCRIPTION
**Pull request by urimandujano**
- Adds section on Globus Auth
- Adds section on Datatypes, validation, caching, and flask helpers
- Better transitions/guiding in docs
- Make graphics fit webpages better
- Merges info pre-existing docs with new docs

To build the docs locally to view via browser:
`cd docs/`
`poetry run make html`
`open build/html/index.html`

### CODE REVIEW

**Comment by urimandujano** [comment]
@jimPruyne this PR is pretty much docs only. While not exactly touching on Flows, it does help round out some of the documentation on ActionProviders (mainly adds sections on Globus Auth to readthedocs)

**Comment by jimPruyne** [comment]
@urimandujano How much of this is new, and how much is refactoring of older docs? There's a lot here, particularly in the changeset, so I want to make sure I"m focusing on the most important bits in reviewing.

Thanks for any pointers that help me narrow it down.

**Comment by urimandujano** [comment]
Good question - most of the content was already in the README.rst under different sections. What this PR does is break the content out into their own RST files and include those new files in the readthedocs source tree.  I merged sections in the README.rst with other docs that were lying around, as well as generally updating and making sure descriptions/instructions were up to date.  The more substantial files are: 

- docs/source/setting_up_auth.rst
- docs/source/toolkit.rst
- docs/source/toolkit/authentication.rst
- docs/source/toolkit/caching.rst
- docs/source/toolkit/data_types.rst
- docs/source/toolkit/flask_helpers.rst
- docs/source/toolkit/validation.rst

**Comment by urimandujano** [comment]
Thanks for the review/contribution! This will hopefully be one of the last dense diffs for the repo.

**Pull request merged**
